/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import Controller.Controller;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Praveen Ingale
 */
public class graph extends javax.swing.JPanel {

    /**
     * Creates new form graph
     */
     BufferedImage img = null;

    public graph() {
        initComponents();
       
        // jLabel1.setIcon(new javax.swing.ImageIcon("E:\\chart8_9.jpg"));
        //jLabel1.setSize(250, 250);
      /* ImageIcon icon = new ImageIcon("E:\\chart8_9.jpg"); 
Image img = icon.getImage(); 
BufferedImage bi = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB); 
Graphics g = bi.createGraphics(); 
g.drawImage(img, 175, 175, 250, 150, null); 
ImageIcon newIcon = new ImageIcon(bi); */
        refresh_icon();
       
  
        //   jLabel1.setSize(500,500);
       // genchart();
    
        
         
    }
    
private Image ScaledImage(Image img, int w, int h)
{
    
    BufferedImage resized=new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
    Graphics2D g2=resized.createGraphics();
    g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    //g2.drawImage(img, w, h, null);
    
    g2.drawImage(img, 0, 0, w, h, null);
    g2.dispose();
    return resized;
}
       public void getimg()
       {
            try {
    img = ImageIO.read(new File("E:\\new.jpg"));
     ImageIcon icon = new ImageIcon(ScaledImage(img,399,220));
     icon.getImage().flush();
    
        jLabel1.setIcon(icon);
         
} catch (IOException e) {
}
       
       }
        
       public void refresh_icon()
       {
           ActionListener actionListener = new ActionListener() {
               @Override
        public void actionPerformed(ActionEvent actionEvent) {
            getimg();
        }
    };
           Timer timer = new Timer(1000, actionListener);
           timer.start();
          
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 201));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
        Controller.getchart();
        //getimg();
        refresh_icon();
        //getimg();
        
        
    }//GEN-LAST:event_jLabel1FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
